version: "3.7"

services:
  api:
    image: hainguyenle89/tradardemocloudapi:latest
    deploy:
      placement:
        constraints: [node.hostname==PTC2SRV19]
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 3001:3000
    #networks:
    #  - ai_net
    volumes:
      - tradardemocloudapi:/usr/src/app/storage
      - /etc/localtime:/etc/localtime:ro

#networks:
#  ai_net:

volumes:
  tradardemocloudapi:
    driver: local
